%----------------------------------------------------------------
% main_Fig_KS.m
%-------------------------------------------------------------------------------------------
% This file plots the Figure for the Kuramoto-Sivashinsky system;
% The figure compares the original/exact time series with the autonomous
% prediction generated by an NGRC reservoir model.
%-------------------------------------------------------------------------------------------
close all
format long;
% h is the sampling time step used when the data were generated.
h=0.01;
% Default line width used in most line plots.
lw2=0.5;
%--------------------------------------------------
color_ex=[0 0.3 1]; % color of original solution
color_rc=[1 0.5 0]; % color of solutions of NGRC
segLength = 80; % period of the same color tone
% Color tones parameters (a1,a2):
% age = k/N;
% alpha = a1 + a2*age;   % older/fainter to newer/darker
% original values:
% a1=0.03;
% a2=0.25;
% probe values:
a1=0.03;
a2=0.5;
lwd=0.7; % linewidth for phase portraits;
%--------------------------------------------------
% Dynamics of the exact system and of NGRC after learning;
% The data file must contain the matrix Xtot with columns:
% time, exact/original signal, and NGRC predicted signal.
%--------------------------------------------------
% Xtot=[Tpr1 U1 XP1];
% save('XPt_record2.mat','Xtot');
% Tpr1 -> time sampling;
% U1 -> exact time series;
% XP1 -> time series of NGRC;
% epsnorm=0.0; Lc_tot=-3.0; h=0.01; tau=0.17; TL=1000;
% bet=1e-7; degree=12; Ndel=4; Tprad_tot=0;
load('Xtot_record.mat');
%--------------------------------------------------
%Xtot=[Tpr1 U1 XP1]; % array from the mat-file
  % Extract and normalize the time coordinate so that plotting starts at t=0.
  Tpr1=Xtot(:,1); % time sampling
  Tpr1=Tpr1-Tpr1(1,1); % time sampling starts from zero
  % Extract the two signals that will be compared in all panels.
  U1=Xtot(:,2); % dynamics of original system
  XP1=Xtot(:,3); % dynamics of autonomous NGRC system  
%-----------------------------------------------------------    
figure

% Coordinates used to place panel labels (a)-(e) inside each subplot.
X1a=[0.5 0.9];
Xat=X1a(1);
Yat=X1a(2);

X1b=[-0.95 0.9];
Xbt=X1b(1);
Ybt=X1b(2);

X1c=[-0.95 0.9];
Xct=X1c(1);
Yct=X1c(2);

X1d=[-0.9 1.8];
Xdt=X1d(1);
Ydt=X1d(2);

X1e=[4 10^(-0.8)];
Xet=X1e(1);
Yet=X1e(2);

% Panel (a): direct time-domain comparison of the exact and NGRC signals.
subplot(3,2,[1 2]);
wideAx=gca;
axes(wideAx);
hold on
plot(Tpr1,U1,'-','color',color_ex,'LineWidth',lw2) % solution of MF equations;
plot(Tpr1,XP1,'-','color',color_rc,'LineWidth',lw2) % solution of MF equations;
hold off
xlim([0,15]);
ylim([-1.1 1.1]);
xlabel('time','Interpreter','latex','FontSize',10);
ylabel('$u$, $\nu$','Interpreter','latex','FontSize',10);
text(Xat,Yat,'(a)','FontSize',10);
leg1=legend('original', 'reservoir', 'Orientation', 'horizontal');
leg1.Position = [0.49 0.95 0.1 0.01];
set(wideAx,'XScale','linear');
set(wideAx,'YScale','linear');

set(wideAx,'XTick',[0 5 10 15]);
set(wideAx,'YTick',[-1 0 1]) 
set(wideAx,'XTickLabel',{'0','5','10','15','Interpreter','latex','FontSize',10})
set(wideAx,'YTickLabel',{'-1','0','1','Interpreter','latex','FontSize',10})
%-----------------------------------------------------------------------------------------------
box on
%------------------------------------------------------------------------------------------------
%--------------------------------------------------------------------------------
% Build delayed-coordinate data for the original system and the NGRC prediction.
% The helper function also prints the valid prediction time.
[Xnow,Xdel,Xnow_ex,Xdel_ex] = plot_KS_dyn(Xtot);
lw2=0.1;

% Panel (b): delayed-coordinate phase portrait of the original/exact system.
subplot(3,2,3);
ha=gca;
axes(ha);
hold on;
%-------------------------------------------------------------
N=size(Xnow_ex,1);
%segLength = 80;
x1=Xnow_ex;
x2=Xdel_ex;

% Plot the trajectory in short segments. The alpha value changes with time,
% which makes the temporal evolution visible in the phase portrait.
for k = 1:segLength:N-segLength
    age = k/N;
    alpha = a1 + a2*age;   % older/fainter to newer/darker
      
    plot(x1(k:k+segLength), x2(k:k+segLength), ...
        'Color',[color_ex alpha], ...
        'LineWidth',lwd);
end
hold off
%-------------------------------------------------------------


set(ha,'XTickLabel','');
set(ha,'XScale','linear');
set(ha,'YScale','linear');
xlabel('$u(t)$','Interpreter','latex','FontSize',10);
ylabel('$u(t-\tau)$','Interpreter','latex','FontSize',10);
text(Xbt,Ybt,'(b)','FontSize',10);

set(ha,'XTick',[-1 0 1]);
set(ha,'YTick',[-1 0 1]) 
set(ha,'XTickLabel',{'-1','0','1','Interpreter','latex','FontSize',10})
set(ha,'YTickLabel',{'-1','0','1','Interpreter','latex','FontSize',10})
%-----------------------------------------------------------------------------------------------
xlim([-1.1,1.1])
ylim([-1.1,1.1])
 box on

% Panel (c): delayed-coordinate phase portrait of the NGRC prediction.
subplot(3,2,4);
ha=gca;
axes(ha);
hold on;
%-------------------------------------------------------------
N=size(Xnow,1)
%segLength = 80;
x1=Xnow;
x2=Xdel;

% Plot NGRC delayed-coordinate trajectory using the same segmented style.
for k = 1:segLength:N-segLength
    age = k/N;
    alpha = a1 + a2*age;   % older/fainter to newer/darker
        
    plot(x1(k:k+segLength), x2(k:k+segLength), ...
        'Color',[color_rc alpha], ...
        'LineWidth',lwd);
end
hold off
%-------------------------------------------------------------


xlabel('$\nu(t)$','Interpreter','latex','FontSize',10);
ylabel('$\nu(t-\tau)$','Interpreter','latex','FontSize',10);
text(Xct,Yct,'(c)','FontSize',10);

set(ha,'XTick',[-1 0 1]);
set(ha,'YTick',[-1 0 1]) 
set(ha,'XTickLabel',{'-1','0','1','Interpreter','latex','FontSize',10})
set(ha,'YTickLabel',{'-1','0','1','Interpreter','latex','FontSize',10})
%-----------------------------------------------------------------------------------------------
xlim([-1.1,1.1])
ylim([-1.1,1.1])
 box on
        % Compute probability density functions for both signals.
        [bin_centers,pdf_ngrc,pdf_exact] = plot_KS_pdf(Xtot);

% Panel (d): statistical comparison through probability density functions.
subplot(3,2,5);
ha=gca;
axes(ha);
plot(bin_centers, pdf_exact,'color',color_ex, 'LineWidth', lw2);
hold on;
plot(bin_centers, pdf_ngrc,'color',color_rc, 'LineWidth', lw2);
hold off;

set(ha,'XTickLabel','');
set(ha,'XScale','linear');
set(ha,'YScale','linear');
xlabel('$u,\nu$','Interpreter','latex','FontSize',10);
ylabel('PDF','Interpreter','latex','FontSize',10);
text(Xdt,Ydt,'(d)','FontSize',10);

set(ha,'XTick',[-1 0 1]);
set(ha,'YTick',[0 1 2]) 
set(ha,'XTickLabel',{'-1','0','1','Interpreter','latex','FontSize',10})
set(ha,'YTickLabel',{'0','1','2','Interpreter','latex','FontSize',10})
%-----------------------------------------------------------------------------------------------
xlim([-1,1])
ylim([0,2])
 box on
%------------------------------------------------------------------------------------------------
%--------------------------------------------------------------------------------
% Power spectral density comparison.
% The PSD can be recomputed with plot_KS_psd, but here it is loaded from a
% precomputed MAT-file to avoid repeating the spectral calculation every run.
  [PSD_exact,PSD_ngrc,f] = plot_KS_psd(Xtot);
% save('KS_psd.mat','f','PSD_exact','PSD_ngrc');
% load('KS_psd.mat');

% Panel (e): frequency-domain comparison using the power spectral density.
subplot(3,2,6);
ha=gca;
semilogy(f, PSD_exact,'color',color_ex, 'LineWidth', lw2);
hold on;
semilogy(f, PSD_ngrc,'color',color_rc, 'LineWidth', lw2);
hold off;

ylabel('Power','Interpreter','latex','FontSize',10);
xlim([0,10])
ylim([1e-8,1])
text(Xet,Yet,'(e)','FontSize',10);

set(ha,'XTick',[0 5 10]);
set(ha,'XTickLabel',{'0','5','10','Interpreter','latex','FontSize',10})
xlabel('Frequency','Interpreter','latex','FontSize',10);
set(ha,'XScale','linear');
set(ha,'YScale','log');

set(ha,'YTick',[1e-8 1e-4 1]) 
set(ha,'YTickLabel',{'10^{-8}','10^{-4}','10^{0}','Interpreter','latex','FontSize',10})
%-----------------------------------------------------------------------------------------------
box on
%------------------------------------------------------------------------------------------------
% Set the physical figure size and export the final figure as an EPS file.
set(gcf,'Units','centimeters')
set(gcf, 'PaperSize', [8.5 11]);
set(gcf,'Position',[2,2,8.5,11]);
saveas(gcf,'Fig_KS','epsc')
