function monomials = generateCheb_feat_vect(X,exponents, degree)
% generates part of the feature vector vith nonlilinearity of the degree
% order
%exponents are generated by the program IndMatr.m
    m = length(X); %  m: embedding dimension, X-row vector of length m
    nd=size(exponents, 1); % number of elements in mononinal with the given degree and m
    % generating Chebychev polynomials of different degree
    XP=zeros(degree+1,m);
    XP(1,:)=ones(1,m);
    XP(2,:)=X;
    for nn=2:degree
        XP(nn+1,:)=2*XP(nn,:).*X-XP(nn-1,:);
    end

    monomials=zeros(nd,1);
    
    % Generate all combinations of exponents that sum to the given degree
    %exponents = generateExponents(m, degree);
    
    % Calculate monomials for each combination of exponents
    for i = 1:nd
        jj=exponents(i,1);
        monomial = XP(jj+1,1);
        for j = 2:m
           jj=exponents(i,j);
           monomial = monomial .* XP(jj+1,j);
        end
        monomials(i) = monomial;
    end
end

